Dev_Personal/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name= 'home'),
    path('blog/', include('blog.urls')),
]

# to display media by user
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT )

blog/urls.py
from django.urls import path
from . import views

# This is just variable that use to clear the app name to Django
app_name = 'blog'

urlpatterns = [
    path('', views.all_blog, name= 'all_blog'),
    path('<int:blog_id>/', views.detail_view, name = 'detail')
]

blog/models.py
from django.db import models


# Create your models here.
class blog_data(models.Model):
    title = models.CharField(max_length=100)
    date = models.DateField()
    description = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class project(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=200)
    image = models.ImageField(upload_to='portfolio/media/')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import blog_data

# Create your views here.
def all_blog(request):
    project_blog_data = blog_data.objects.order_by()
    return render(request, 'blog.html', {'project_blog_data':project_blog_data})

def detail_view(request, blog_id):
    blog = get_object_or_404(blog_data, pk = blog_id)
    return render(request, 'detail_view.html', {'blog_dta':blog})

portfolio/views.py
from django.shortcuts import render
from .models import project

# Create your views here.

def home(request):
    project_data = project.objects.all()
    return render(request, "home.html", {'data':project_data})

blog/templates/blog.html
<! -- extends - used for carry all the lines of particular html content into this class -->
{% extends 'bootstrap_content.html' %}

< !-- block - used for overriding the template -->
{% block content %}

<h1 id = "blogtitle" class="font-weight text-center my-3" style="color: cadetblue">This is blog</h1>

<h3 class="font-weight text-center"> Prasanth has created {{project_blog_data.count}} blog{{ project_blog_data.count|pluralize }}</h3>

<br>
{% for blog in project_blog_data %}

<div class="row justify-content-center my-3">
    <div class="col-md-12">

        <! -- blog:detail the blog is just name use for not get into confuse if there are multi name with the same -->
        <a href="{% url 'blog:detail' blog.id %}">
         <h1>{{ blog.title }}</h1>
        </a>

        <! -- To get particular format of the date |date: format is used -->
        <h3 class="text-muted">{{ blog.date| date:'d M y' | upper }}</h3>

        <! -- striptags - To avoid html tag's if given while entering data
              safe      - It is used to effect the data if any html tags enter -- >
        <h4>{{ blog.description|striptags|truncatechars:100 }}</h4>

    </div>
</div>


{% endfor %}
{% endblock %}

blog/templates/detail_view.html
<! -- extends - used for carry all the lines of particular html content into this class -->
{% extends 'bootstrap_content.html' %}

< !-- block - used for overriding the template -->
{% block content %}

<h1 class="font-weight text-center my-4">{{ blog_dta.title }}</h1>
<h2 class="font-weight text-center my-4" style="color: gray">{{ blog_dta.date|date:'F jS Y' }}</h2>
<h5 align="justify">{{ blog_dta.description|safe }}</h5>

{% endblock %}

portfolio/templates/bootstrap_content.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static "portfolio/custom.css" %}">
    <link href="https://fonts.googleapis.com/css2?family=Piedra&display=swap" rel="stylesheet">
    <link rel="icon" type="image/png"  href="{% static "portfolio/Logo.png" %}">
    <title>Prasanth's 😊</title>
  </head>
  <body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">

      <div class="container">

        <!-- This is used to add logo,text, link to the nav bar -->
        <a class="navbar-brand" href="{% url 'home' %}">
            <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="Guru Logo">
            <span>Prasanth Sai</span>
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
           <span class="navbar-toggler-icon"></span>
        </button>

        <!-- This line make full nav bar content into center -->
        <div class="collapse navbar-collapse text-center" id="navbarNav">
           <ul class="navbar-nav ml-auto">
               <li class="nav-item">
                 <a class="nav-link" href="{% static "portfolio/Prasanth Resume.pdf" %}">Resume</a>
               </li>
               <li class="nav-item">
                 <a class="nav-link" href="https://www.linkedin.com/in/prasanth-gurusai-8301808a/" target="_blank">LinkedIn</a>
               </li>
               <li class="nav-item">
                   <!-- target="_blank" is used for open url in new tab -->
                 <a class="nav-link" href="https://www.instagram.com/prasanthstarone/" target="_blank">Instagram</a>
               </li>
               <li class="nav-item">
                 <a role="button" href="{% url 'blog:all_blog' %}" class="btn btn-primary">Blog</a>
               </li>
           </ul>
        </div>
      </div>
   </nav>

  <!-- Containers used for giving 15 pixel padding by default from left and right-->
  <div class="container">
      {% block content %}{% endblock %}
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

portfolio/templates/home.html
<! -- extends - used for carry all the lines of particular html content into this class -->
{% extends 'bootstrap_content.html' %}
{% load static %}
< !-- block - used for overriding the template -->
{% block content %}

    <!-- Below code is for making image center and margins -->
<div class="row justify-content-center my-5">
 <div class="col-6">
     <img src="{% static 'portfolio/Myfav.jpg' %}" class="img-fluid">
 </div>
</div>

    <!-- Below code is for making text center, font and margins -->
<div class="row justify-content-center my-3">
  <h1 id="hometext">Welcome to Prasanth's World</h1>
</div>

<h2 class="my-3 ml-3">Portfolio</h2>
<hr>

<div class="row">
   {% for project_data in data %}

   <div class="col-md-4">

     {% if project_data.url %}
      <a href="{{ project_data.url }}">
        <img src="{{ project_data.image.url }}" class="img-fluid mb=3">
      </a>

      {% else %}
        <img src="{{ project_data.image.url }}" class="img-fluid mb=3">

      {% endif %}

       <div style="background: rgba(168,168,167,0.11)">
          <h2>{{ project_data.title }}</h2>
          <p class="ml-3">--{{ project_data.description }}</p>
       </div>


   </div>
    {% endfor %}
</div>

{% endblock %}